CREATE TABLE IF NOT EXISTS sensors (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    model VARCHAR(50), -- Useful to track hardware types (e.g., 'ESP32', 'DHT22')
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(name, model)
);

CREATE TABLE IF NOT EXISTS locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS readings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sensor_id INTEGER NOT NULL REFERENCES sensors(id),
    location_id INTEGER REFERENCES locations(id), -- Optional: remove if sensors never move
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    -- Readings (Standardized: Celsius, %, hPa, ppm)
    temperature REAL, 
    humidity REAL,
    pressure REAL,
    co2 REAL
);

-- CRITICAL: Indexes for performance
-- 1. Quickly find all readings for a specific sensor, ordered by time (latest first)
CREATE INDEX idx_readings_sensor_time ON readings (sensor_id, recorded_at DESC);

-- 2. Quickly find all readings for a specific location (e.g., "Kitchen temps")
CREATE INDEX idx_readings_location_time ON readings (location_id, recorded_at DESC);


