CREATE TABLE IF NOT EXISTS sensors (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    model VARCHAR(50), -- Useful to track hardware types (e.g., 'ESP32', 'DHT22')
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(name, model)
);

CREATE TABLE IF NOT EXISTS locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE(name)
);

-- Environment Data
CREATE TABLE IF NOT EXISTS environment_data (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sensor_id INTEGER NOT NULL REFERENCES sensors(id),
    location_id INTEGER NOT NULL REFERENCES locations(id), -- Optional: remove if sensors never move
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    -- environment_data (Standardized: Celsius, %, hPa, ppm)
    temperature REAL, 
    humidity REAL,
    pressure REAL,
    co2 REAL
);

-- CRITICAL: Indexes for performance
-- 1. Quickly find all environment_data for a specific sensor, ordered by time (latest first)
CREATE INDEX idx_environment_data_sensor_time ON environment_data (sensor_id, recorded_at DESC);

-- 2. Quickly find all environment_data for a specific location (e.g., "Kitchen temps")
CREATE INDEX idx_environment_data_location_time ON environment_data (location_id, recorded_at DESC);

-- Soil Data
CREATE TABLE IF NOT EXISTS soil_data (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sensor_id INTEGER NOT NULL REFERENCES sensors(id),
    location_id INTEGER NOT NULL REFERENCES locations(id), -- Optional: remove if sensors never move
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    
    -- soil_data (Standardized: %m, ADC counts)
    moisture REAL NOT NULL, 
    adc INTEGER,
);

CREATE INDEX idx_soil_sensor_time ON soil_data (sensor_id, recorded_at DESC);
CREATE INDEX idx_soil_location_time ON soil_data (location_id, recorded_at DESC);